apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: chat-app
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL21vbmdvYWRtaW46c2VjcmV0QG1vbmdvZGI6MjcwMTcvZGJuYW1lP2F1dGhTb3VyY2U9YWRtaW4= 
  #mongodb://mongoadmin:secret@mongodb:27017/dbname?authSource=admin