apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: chat-app
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL21vbmdvYWRtaW46c2VjcmV0QG1vbmdvZGI6MjcwMTcvY2hhdEFwcD9hdXRoU291cmNlPWFkbWlu
  #mongodb://mongoadmin:secret@mongodb:27017/chatApp?authSource=admin