---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kubeissuer-ripon
  namespace: chat-app
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: syedkamruzzamanripon@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: kubeissuer-chat-app
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubecert-chat-app
  namespace: chat-app
spec:
  secretName: chat-app-tls
  issuerRef:
    name: kubeissuer-ripon
    kind: ClusterIssuer
  commonName: ripon2.syed-kamruzzaman.com
  dnsNames:
  - ripon2.syed-kamruzzaman.com
